const FROM_SET = 'FROM_SET';
const TO_SET = 'TO_SET';
const NUM_SET = 'NUM_SET';
const RESULT_COUNT = 'RESULT_COUNT';
const FROM_TO_REVERSE = 'FROM_TO_REVERSE';

export default {
  FROM_SET,
  TO_SET,
  NUM_SET,
  RESULT_COUNT,
  FROM_TO_REVERSE
}
